### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by chalard87** [YanKlInnomme/FoundryVTT-k4lt-fr#1]
bonjour,
après installation, je l'espère, complète,  (babele, kult assets, kult extra fr, libwrapper) et installation de l'aventure
 galerie des âmes, certains documents n'apparaissent pas (icone de lien perdu) : lettre de "lire la lettre", lettres du studio de starker.
Et l'icone Kult qui se situe normalement au dessus des icones d'outils de Foundry est elle aussi broken.
J'en profite pour vous remercier pour ce boulot incroyable de qualité.
![Foundry_Virtual_Tabletop_IDT5MUVeYP](https://github.com/YanKlInnomme/FoundryVTT-k4lt-fr/assets/45460274/257cb49a-ad5a-4c2b-841b-9b9ca44b0351)
![Foundry_Virtual_Tabletop_niNEGfYPx7](https://github.com/YanKlInnomme/FoundryVTT-k4lt-fr/assets/45460274/b08408ab-1969-476b-a855-3aabff29050c)
![Foundry_Virtual_Tabletop_rlhLeMt2pg](https://github.com/YanKlInnomme/FoundryVTT-k4lt-fr/assets/45460274/896da704-74b1-48c0-a5f8-698fc1f190b6)

**Comment by YanKlInnomme** [comment]
C'est vraiment bizarre, cela fonctionne chez moi, regarde :
https://github.com/YanKlInnomme/FoundryVTT-k4lt-fr/assets/100078854/e1aad5e9-a634-498a-ae0f-d461d7b780cc

Lorsque tu actives la console avec la touche F12, tu as des messages d'erreur ? Je veux savoir quel chemin est erroné exactement.

**Comment by chalard87** [comment]
voici une vidéo reproduisant le problème https://1drv.ms/v/s!Aq94oZ32i0Fzk7ZFIVVNpjIJpVUSjw?e=uCPCrW
et le log 
[localhost-1720719328147.log](https://github.com/user-attachments/files/16181630/localhost-1720719328147.log)
Je fais probablement une erreur qq part, désolé pour le dérangement !

**Comment by YanKlInnomme** [comment]
J'ai trouvé. Il manque le dossier img dans l'archive. Je corrige et je publie une nouvelle version. Merci de m'avoir signalé le problème.

**Comment by chalard87** [comment]
Super ! merci.
